# Generated by Django 5.0.7 on 2024-10-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_middle_name', models.CharField(blank=True, max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_phone_number', models.BigIntegerField()),
                ('user_country', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('user_address_line_1', models.CharField()),
                ('user_password', models.CharField()),
                ('user_status', models.BooleanField(default=False)),
                ('user_hold', models.BooleanField(default=False)),
                ('user_type', models.CharField()),
                ('user_state', models.CharField()),
                ('user_pin_code', models.CharField()),
                ('profile_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_amount', models.CharField(max_length=255)),
                ('transaction_status', models.CharField()),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionUser',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('user_phone_number', models.BigIntegerField()),
                ('transaction_currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': False,
            },
        ),
    ]
